networks:
  winecellar:
      driver: bridge

services:
  postgres:
    image: postgres:14.2
    environment:
      POSTGRES_USER: pguser
      POSTGRES_PASSWORD: QaZrAJykbvdzNBR94V8m6XuTYx7nfqjUpcHtFPKw
    volumes:
      - winecellar-postgres:/var/lib/postgresql/data
    networks:
      - winecellar

  redis:
    image: redis:7.0
    volumes:
      - winecellar-redis:/var/lib/redis/data
    networks:
      - winecellar

  winecellar:
    build:
      context: .
    volumes:
      - ./winecellar:/opt/app
    links:
      - postgres
      - redis
    ports:
      - '8010:8010'
    env_file:
      - .env
    networks:
      - winecellar

volumes:
  winecellar-postgres:
  winecellar-redis: